# 网站基本信息
title: "Blog"
description: "YYYYYYYY"
baseurl: ""
url: "https://ziqiyang107.github.io"

# Jekyll 设置
markdown: kramdown
highlighter: rouge
permalink: /:title/
future: false

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# MathJax 设置
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# 其他设置
timezone: Asia/Shanghai
encoding: utf-8
